
ignored = ["golang.org/x/text", "golang.org/x/sys", "golang.org/x/net", "go", "github.com/therecipe/qt/*"]

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.1.3"
