
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["golang.org/x/text", "golang.org/x/sys", "golang.org/x/net", "go"]

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang-ui/nuklear"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.1.3"
