name: lyricfier
base: core18
version: '0.1'
summary: Lyrics search for Spotify app
description: |
  Lyricfiers lyrics for Spotify.
grade: stable
confinement: strict

parts:
  lyricfier:
    plugin: go
    go-importpath: github.com/emilioastarita/lyricfier2
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  lyricfier:
    command: bin/lyricfier
    plugs:
      - mpris
      - network
      - network-bind

