name: Make release for all platforms
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: install runsim
        run: |
          go get -u github.com/mjibson/esc
          sudo apt-get -y install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - uses: actions/checkout@v2
      - name: Release on Windows
        run: make release-windows
        shell: bash
      - name: Releases
        run: |
          make release-linux
          make release-darwin
          make release-windows
      - uses: actions/upload-artifact@v2
        with:
          name: lyricfier-linux-amd64
          path: build/lyricfier-linux-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: lyricfier-darwin-amd64
          path: "build/lyricfier-darwin-amd64"
      - uses: actions/upload-artifact@v2
        with:
          name: lyricfier-windows-amd64.exe
          path: "build/lyricfier-windows-amd64.exe"
